package com.euler;

/**
 Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

 Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
 Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
 Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
 It can be verified that T285 = P165 = H143 = 40755.

 Find the next triangle number that is also pentagonal and hexagonal.
 */
public class Problem45 {

    public static void main(String[] args) {
        Problem45 p45 = new Problem45();
        p45.run();
    }

    private void run() {
        boolean found = false;
        int i = 1;
        long hexagon;
        while (!found) {
            hexagon = i * (2 * i - 1);
            if (isPentagonal(hexagon) && isTriangular(hexagon)) {
                System.out.println(hexagon);
                if (hexagon > 40755) {
                    found = true;
                }
            }
            i++;
        }
    }

    private boolean isTriangular(long t) {
        double tritest = (Math.sqrt(8 * t + 1.0) - 1.0) / 2.0;
        return tritest == (int) tritest;
    }

    private boolean isPentagonal(long p) {
        // p = 1 / 24 * (36n^2 - 12n + 1 - 1) = 1 / 24 * ((6n - 1)^2 - 1)
        double penistest = (Math.sqrt(24 * p + 1.0) + 1.0) / 6.0;
        return penistest == (int) penistest;
    }

    private boolean isHexagonal(long h) {
        // h = 1 / 8 * (16n^2 - 8n + 1 - 1) = 1 / 8 * ((4n - 1)^2 - 1)
        double hextest = (Math.sqrt(8 * h + 1.0) + 1) / 4.0;
        return hextest == (int) hextest;
    }
}
